-- AlterTable
ALTER TABLE "Contact" ALTER COLUMN "createDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Hero_Section" ALTER COLUMN "createDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createDate" SET DEFAULT CURRENT_TIMESTAMP;
